[debug] [2023-05-14T05:07:07.475Z] ----------------------------------------------------------------------
[debug] [2023-05-14T05:07:07.476Z] Command:       C:\laragon\bin\nodejs\node-v18\node.exe C:\Users\ASUS\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2023-05-14T05:07:07.476Z] CLI Version:   11.25.2
[debug] [2023-05-14T05:07:07.476Z] Platform:      win32
[debug] [2023-05-14T05:07:07.476Z] Node Version:  v18.8.0
[debug] [2023-05-14T05:07:07.480Z] Time:          Sun May 14 2023 13:07:07 GMT+0800 (China Standard Time)
[debug] [2023-05-14T05:07:07.480Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-05-14T05:07:07.482Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2023-05-14T05:07:07.556Z] Object "" in "firebase.json" has unknown property: {"additionalProperty":"type"}
[info] Already logged in as nurfarid776@gmail.com
[debug] [2023-05-14T05:07:09.052Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2023-05-14T05:07:09.052Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2023-05-14T05:07:13.677Z] Error: Timed out.
    at Timeout.<anonymous> (C:\Users\ASUS\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:253:49)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
[error] 
[error] Error: An unexpected error has occurred.
